import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-federal-contract-indirect-rate-reconciliation",
  "engine": "recovery",
  "title": "Federal Contract Indirect Rate Reconciliation",
  "shortTitle": "Federal Contract Indirect Rate Reconciliation",
  "tagline": "Calculate final indirect rates, reconcile provisional billings, and recover allowable contract revenue.",
  "industry": "Government Contract Finance",
  "buyer": "Federal contractors and professional services firms",
  "uiPort": 4693,
  "apiPort": 5693,
  "accent": "#0369a1",
  "currency": "USD",
  "primaryOutcome": "Federal Contract Indirect Rate Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect contracts, provisional billing rates, direct labor, indirect pools, allocation bases, unallowable costs, invoices, final rates, and payments in one accountable workflow. Calculate final indirect rates, reconcile provisional billings, and recover allowable contract revenue.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Federal Contract Indirect Rate Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("contract-clause-library","FCI01","Contract clause library","Execute contract clause library using contracts, provisional billing rates, direct labor, indirect pools, allocation bases, unallowable costs, invoices, final rates, and payments.","Produce a governed contract clause library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Contract / Fiscal Year","text","Contract / Fiscal Year · Standard Case"],["caseReference","Contract clause library Reference","text","FCI01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1195000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1445950],["domainDriver","Rate Pool","select","Fringe",["Fringe","Overhead","G&A"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract clause library case","Fiscal year rate structure case","Direct cost ingestion case","Fringe pool calculation case","Overhead pool calculation case"]}),
feature("fiscal-year-rate-structure","FCI02","Fiscal year rate structure","Execute fiscal year rate structure using contracts, provisional billing rates, direct labor, indirect pools, allocation bases, unallowable costs, invoices, final rates, and payments.","Produce a governed fiscal year rate structure decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Contract / Fiscal Year","text","Contract / Fiscal Year · Standard Case"],["caseReference","Fiscal year rate structure Reference","text","FCI02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1195000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1445950],["domainDriver","Rate Pool","select","Fringe",["Fringe","Overhead","G&A"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract clause library case","Fiscal year rate structure case","Direct cost ingestion case","Fringe pool calculation case","Overhead pool calculation case"]}),
feature("direct-cost-ingestion","FCI03","Direct cost ingestion","Execute direct cost ingestion using contracts, provisional billing rates, direct labor, indirect pools, allocation bases, unallowable costs, invoices, final rates, and payments.","Produce a governed direct cost ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Contract / Fiscal Year","text","Contract / Fiscal Year · Standard Case"],["caseReference","Direct cost ingestion Reference","text","FCI03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1195000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1445950],["domainDriver","Rate Pool","select","Fringe",["Fringe","Overhead","G&A"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract clause library case","Fiscal year rate structure case","Direct cost ingestion case","Fringe pool calculation case","Overhead pool calculation case"]}),
feature("fringe-pool-calculation","FCI04","Fringe pool calculation","Execute fringe pool calculation using contracts, provisional billing rates, direct labor, indirect pools, allocation bases, unallowable costs, invoices, final rates, and payments.","Produce a governed fringe pool calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Contract / Fiscal Year","text","Contract / Fiscal Year · Standard Case"],["caseReference","Fringe pool calculation Reference","text","FCI04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1195000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1445950],["domainDriver","Rate Pool","select","Fringe",["Fringe","Overhead","G&A"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract clause library case","Fiscal year rate structure case","Direct cost ingestion case","Fringe pool calculation case","Overhead pool calculation case"]}),
feature("overhead-pool-calculation","FCI05","Overhead pool calculation","Execute overhead pool calculation using contracts, provisional billing rates, direct labor, indirect pools, allocation bases, unallowable costs, invoices, final rates, and payments.","Produce a governed overhead pool calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Contract / Fiscal Year","text","Contract / Fiscal Year · Standard Case"],["caseReference","Overhead pool calculation Reference","text","FCI05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1195000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1445950],["domainDriver","Rate Pool","select","Fringe",["Fringe","Overhead","G&A"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract clause library case","Fiscal year rate structure case","Direct cost ingestion case","Fringe pool calculation case","Overhead pool calculation case"]}),
feature("ganda-pool-calculation","FCI06","G&A pool calculation","Execute g&a pool calculation using contracts, provisional billing rates, direct labor, indirect pools, allocation bases, unallowable costs, invoices, final rates, and payments.","Produce a governed g&a pool calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Contract / Fiscal Year","text","Contract / Fiscal Year · Standard Case"],["caseReference","G&A pool calculation Reference","text","FCI06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1195000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1445950],["domainDriver","Rate Pool","select","Fringe",["Fringe","Overhead","G&A"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract clause library case","Fiscal year rate structure case","Direct cost ingestion case","Fringe pool calculation case","Overhead pool calculation case"]}),
feature("allocation-base-validation","FCI07","Allocation base validation","Execute allocation base validation using contracts, provisional billing rates, direct labor, indirect pools, allocation bases, unallowable costs, invoices, final rates, and payments.","Produce a governed allocation base validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Contract / Fiscal Year","text","Contract / Fiscal Year · Standard Case"],["caseReference","Allocation base validation Reference","text","FCI07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1195000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1445950],["domainDriver","Rate Pool","select","Fringe",["Fringe","Overhead","G&A"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract clause library case","Fiscal year rate structure case","Direct cost ingestion case","Fringe pool calculation case","Overhead pool calculation case"]}),
feature("unallowable-cost-exclusion","FCI08","Unallowable cost exclusion","Execute unallowable cost exclusion using contracts, provisional billing rates, direct labor, indirect pools, allocation bases, unallowable costs, invoices, final rates, and payments.","Produce a governed unallowable cost exclusion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Contract / Fiscal Year","text","Contract / Fiscal Year · Standard Case"],["caseReference","Unallowable cost exclusion Reference","text","FCI08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1195000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1445950],["domainDriver","Rate Pool","select","Fringe",["Fringe","Overhead","G&A"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract clause library case","Fiscal year rate structure case","Direct cost ingestion case","Fringe pool calculation case","Overhead pool calculation case"]}),
feature("provisional-billing-reconciliation","FCI09","Provisional billing reconciliation","Execute provisional billing reconciliation using contracts, provisional billing rates, direct labor, indirect pools, allocation bases, unallowable costs, invoices, final rates, and payments.","Produce a governed provisional billing reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Contract / Fiscal Year","text","Contract / Fiscal Year · Standard Case"],["caseReference","Provisional billing reconciliation Reference","text","FCI09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1195000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1445950],["domainDriver","Rate Pool","select","Fringe",["Fringe","Overhead","G&A"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract clause library case","Fiscal year rate structure case","Direct cost ingestion case","Fringe pool calculation case","Overhead pool calculation case"]}),
feature("final-rate-calculation","FCI10","Final rate calculation","Execute final rate calculation using contracts, provisional billing rates, direct labor, indirect pools, allocation bases, unallowable costs, invoices, final rates, and payments.","Produce a governed final rate calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Contract / Fiscal Year","text","Contract / Fiscal Year · Standard Case"],["caseReference","Final rate calculation Reference","text","FCI10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1195000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1445950],["domainDriver","Rate Pool","select","Fringe",["Fringe","Overhead","G&A"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract clause library case","Fiscal year rate structure case","Direct cost ingestion case","Fringe pool calculation case","Overhead pool calculation case"]}),
feature("funding-ceiling-control","FCI11","Funding ceiling control","Execute funding ceiling control using contracts, provisional billing rates, direct labor, indirect pools, allocation bases, unallowable costs, invoices, final rates, and payments.","Produce a governed funding ceiling control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Contract / Fiscal Year","text","Contract / Fiscal Year · Standard Case"],["caseReference","Funding ceiling control Reference","text","FCI11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1195000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1445950],["domainDriver","Rate Pool","select","Fringe",["Fringe","Overhead","G&A"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract clause library case","Fiscal year rate structure case","Direct cost ingestion case","Fringe pool calculation case","Overhead pool calculation case"]}),
feature("completion-invoice-preparation","FCI12","Completion invoice preparation","Execute completion invoice preparation using contracts, provisional billing rates, direct labor, indirect pools, allocation bases, unallowable costs, invoices, final rates, and payments.","Produce a governed completion invoice preparation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Contract / Fiscal Year","text","Contract / Fiscal Year · Standard Case"],["caseReference","Completion invoice preparation Reference","text","FCI12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1195000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1445950],["domainDriver","Rate Pool","select","Fringe",["Fringe","Overhead","G&A"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract clause library case","Fiscal year rate structure case","Direct cost ingestion case","Fringe pool calculation case","Overhead pool calculation case"]}),
feature("government-negotiation-support","FCI13","Government negotiation support","Execute government negotiation support using contracts, provisional billing rates, direct labor, indirect pools, allocation bases, unallowable costs, invoices, final rates, and payments.","Produce a governed government negotiation support decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Contract / Fiscal Year","text","Contract / Fiscal Year · Standard Case"],["caseReference","Government negotiation support Reference","text","FCI13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1195000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1445950],["domainDriver","Rate Pool","select","Fringe",["Fringe","Overhead","G&A"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract clause library case","Fiscal year rate structure case","Direct cost ingestion case","Fringe pool calculation case","Overhead pool calculation case"]}),
feature("cash-recovery-tracking","FCI14","Cash recovery tracking","Execute cash recovery tracking using contracts, provisional billing rates, direct labor, indirect pools, allocation bases, unallowable costs, invoices, final rates, and payments.","Produce a governed cash recovery tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Contract / Fiscal Year","text","Contract / Fiscal Year · Standard Case"],["caseReference","Cash recovery tracking Reference","text","FCI14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1195000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1445950],["domainDriver","Rate Pool","select","Fringe",["Fringe","Overhead","G&A"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract clause library case","Fiscal year rate structure case","Direct cost ingestion case","Fringe pool calculation case","Overhead pool calculation case"]}),
feature("contract-rate-analytics","FCI15","Contract rate analytics","Execute contract rate analytics using contracts, provisional billing rates, direct labor, indirect pools, allocation bases, unallowable costs, invoices, final rates, and payments.","Produce a governed contract rate analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Contract / Fiscal Year","text","Contract / Fiscal Year · Standard Case"],["caseReference","Contract rate analytics Reference","text","FCI15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1195000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1445950],["domainDriver","Rate Pool","select","Fringe",["Fringe","Overhead","G&A"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Contract clause library case","Fiscal year rate structure case","Direct cost ingestion case","Fringe pool calculation case","Overhead pool calculation case"]})
]);
